name: Build LaTeX PDF

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile LaTeX
      uses: xu-cheng/latex-action@3.2.0
      with: 
        root_file:
          main.tex
          
    - name: Commit PDF to repository
      run: |
        git config --global user.name kindun
        git config --global user.email suzudai2118@gmail.com
        git add main.pdf
        git commit -m "Add PDF output"
        git push
      
