name: Build LaTeX PDF

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile LaTeX
      uses: xu-cheng/latex-action@3.2.0
      with: 
        root-file:
          main.tex
          
    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: output-pdf
        path: main.pdf
