name: Build LaTeX PDF

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up TeX Live
      uses: teatimeguest/setup-texlive-action@v2

    - name: Install packages
      run: |
        tlmgr install latexmk scheme-basic

    - name: Compile LaTeX
      run: |
        latexmk -pdf main.tex

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: output-pdf
        path: ../../main.pdf
